name: Deploy to EC2 on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t darshan0011/react-todo .

      - name: Push Docker image to Docker Hub
        run: docker push darshan0011/react-todo

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ec2-13-60-182-30.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy Docker container to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@ec2-13-60-182-30.eu-north-1.compute.amazonaws.com << 'EOF'
            docker pull darshan0011/react-todo
            docker stop react-todo || true
            docker rm react-todo || true
            docker run -d -p 3001:80 --name react-todo darshan0011/react-todo
          EOF
